title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nobuntu-br.github.io" # the base hostname & protocol for your site, e.g. http://example.com
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache

navigation:
  - title: "Início"
    url: "/"
  - title: "Introdução"
    url: "/introducao/"
  - title: "Guia de Uso"
    url: "/guia/"
  - title: "Referência"
    url: "/referencia/"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
